
name: Nuclei - DAST Scan

on: [push]

jobs:
  nuclei-scan:
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Install Node.js 14.x
       uses: actions/setup-node@v2
       with:
         node-version: 14.x
     - name: Install Dependencies
       run: npm clean-install
     - uses: actions/setup-go@v2
       with:
           go-version: 1.17
     - name: Run Application
       run: nohup npm run start &
     - name: Nuclei - DAST Scan
       uses: projectdiscovery/nuclei-action@main
       with:
           target: http://localhost:3000
           markdown-export: vuln_node_express

     - name: GitHub Workflow artifacts
       uses: actions/upload-artifact@v2
       with:
          name: nuclei.log
          path: nuclei.log

     - name: GitHub Security Dashboard Alerts update
       uses: github/codeql-action/upload-sarif@v1
       with:
          sarif_file: nuclei.sarif
